In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
df1= pd.read_csv("concatenated.csv")
train_p = pd.read_csv("train_prompts.csv")
train_e=pd.read_csv("train_essays.csv")
test = pd.read_csv("test_essays.csv")
sample = pd.read_csv("sample_submission.csv")

In [3]:
df1.drop(columns=['id','prompt_id','model','kaggle_repo'],inplace = True)

In [4]:
df1

                                                    text  generated
0      Advantages of Limiting Car Usage \n\nLimiting ...          1
1      Advantages of Limiting Car Usage\n\nLimiting c...          1
2      Limiting car usage has numerous advantages tha...          1
3      The passages provided discuss the advantages o...          1
4      Title: The Advantages of Limiting Car Usage\n\...          1
...                                                  ...        ...
54686  I believe using cellphones in class for educat...          0
54687  Working alone, students do not have to argue w...          0
54688  "A problem is a chance for you to do your best...          0
54689  Many people disagree with Albert Schweitzer's ...          0
54690  Do you think that failure is the main thing fo...          0

[54691 rows x 2 columns]

In [5]:
train_p

,prompt_id,prompt_name,instructions,source_text
0,0,Car-free cities,Write an explanatory essay to inform fellow ci...,"# In German Suburb, Life Goes On Without Cars ..."
1,1,Does the electoral college work?,Write a letter to your state senator in which ...,# What Is the Electoral College? by the Office...

In [6]:
train_e

,id,prompt_id,text,generated
0,0059830c,0,Cars. Cars have been around since they became ...,0
1,005db917,0,Transportation is a large necessity in most co...,0
2,008f63e3,0,"""America's love affair with it's vehicles seem...",0
3,00940276,0,How often do you ride in a car? Do you drive a...,0
4,00c39458,0,Cars are a wonderful thing. They are perhaps o...,0
...,...,...,...,...
1373,fe6ff9a5,1,There has been a fuss about the Elector Colleg...,0
1374,ff669174,0,Limiting car usage has many advantages. Such a...,0
1375,ffa247e0,0,There's a new trend that has been developing f...,0
1376,ffc237e9,0,As we all know cars are a big part of our soci...,0
1377,ffe1ca0d,0,Cars have been around since the 1800's and hav...,0

In [7]:
merged_df = pd.merge(train_e, train_p, on='prompt_id')

In [8]:
merged_df

,id,prompt_id,text,generated,prompt_name,instructions,source_text
0,0059830c,0,Cars. Cars have been around since they became ...,0,Car-free cities,Write an explanatory essay to inform fellow ci...,"# In German Suburb, Life Goes On Without Cars ..."
1,005db917,0,Transportation is a large necessity in most co...,0,Car-free cities,Write an explanatory essay to inform fellow ci...,"# In German Suburb, Life Goes On Without Cars ..."
2,008f63e3,0,"""America's love affair with it's vehicles seem...",0,Car-free cities,Write an explanatory essay to inform fellow ci...,"# In German Suburb, Life Goes On Without Cars ..."
3,00940276,0,How often do you ride in a car? Do you drive a...,0,Car-free cities,Write an explanatory essay to inform fellow ci...,"# In German Suburb, Life Goes On Without Cars ..."
4,00c39458,0,Cars are a wonderful thing. They are perhaps o...,0,Car-free cities,Write an explanatory essay to inform fellow ci...,"# In German Suburb, Life Goes On Without Cars ..."
...,...,...,...,...,...,...,...
1373,fc66f374,1,The Electoral College was originally establish...,0,Does the electoral college work?,Write a letter to your state senator in which ...,# What Is the Electoral College? by the Office...
1374,fcb87d59,1,"Dear senator, I think that the presidential el...",0,Does the electoral college work?,Write a letter to your state senator in which ...,# What Is the Electoral College? by the Office...
1375,fcd93e2d,1,The electoral college is a group of electors t...,0,Does the electoral college work?,Write a letter to your state senator in which ...,# What Is the Electoral College? by the Office...
1376,fcfe84cb,1,An electoral College compromises between elect...,0,Does the electoral college work?,Write a letter to your state senator in which ...,# What Is the Electoral College? by the Office...
1377,fe6ff9a5,1,There has been a fuss about the Elector Colleg...,0,Does the electoral college work?,Write a letter to your state senator in which ...,# What Is the Electoral College? by the Office...

In [9]:
merged_df['text'] = merged_df['text']+' '+merged_df['source_text'] + ' ' + merged_df['instructions']

In [10]:
merged_df

,id,prompt_id,text,generated,prompt_name,instructions,source_text
0,0059830c,0,Cars. Cars have been around since they became ...,0,Car-free cities,Write an explanatory essay to inform fellow ci...,"# In German Suburb, Life Goes On Without Cars ..."
1,005db917,0,Transportation is a large necessity in most co...,0,Car-free cities,Write an explanatory essay to inform fellow ci...,"# In German Suburb, Life Goes On Without Cars ..."
2,008f63e3,0,"""America's love affair with it's vehicles seem...",0,Car-free cities,Write an explanatory essay to inform fellow ci...,"# In German Suburb, Life Goes On Without Cars ..."
3,00940276,0,How often do you ride in a car? Do you drive a...,0,Car-free cities,Write an explanatory essay to inform fellow ci...,"# In German Suburb, Life Goes On Without Cars ..."
4,00c39458,0,Cars are a wonderful thing. They are perhaps o...,0,Car-free cities,Write an explanatory essay to inform fellow ci...,"# In German Suburb, Life Goes On Without Cars ..."
...,...,...,...,...,...,...,...
1373,fc66f374,1,The Electoral College was originally establish...,0,Does the electoral college work?,Write a letter to your state senator in which ...,# What Is the Electoral College? by the Office...
1374,fcb87d59,1,"Dear senator, I think that the presidential el...",0,Does the electoral college work?,Write a letter to your state senator in which ...,# What Is the Electoral College? by the Office...
1375,fcd93e2d,1,The electoral college is a group of electors t...,0,Does the electoral college work?,Write a letter to your state senator in which ...,# What Is the Electoral College? by the Office...
1376,fcfe84cb,1,An electoral College compromises between elect...,0,Does the electoral college work?,Write a letter to your state senator in which ...,# What Is the Electoral College? by the Office...
1377,fe6ff9a5,1,There has been a fuss about the Elector Colleg...,0,Does the electoral college work?,Write a letter to your state senator in which ...,# What Is the Electoral College? by the Office...

In [11]:
df = merged_df.drop(columns = ['id','prompt_name','instructions','source_text'])

In [12]:
df

      prompt_id                                               text  generated
0             0  Cars. Cars have been around since they became ...          0
1             0  Transportation is a large necessity in most co...          0
2             0  "America's love affair with it's vehicles seem...          0
3             0  How often do you ride in a car? Do you drive a...          0
4             0  Cars are a wonderful thing. They are perhaps o...          0
...         ...                                                ...        ...
1373          1  The Electoral College was originally establish...          0
1374          1  Dear senator, I think that the presidential el...          0
1375          1  The electoral college is a group of electors t...          0
1376          1  An electoral College compromises between elect...          0
1377          1  There has been a fuss about the Elector Colleg...          0

[1378 rows x 3 columns]

In [13]:
df.drop(columns = ['prompt_id'],inplace = True)

In [14]:
df

                                                   text  generated
0     Cars. Cars have been around since they became ...          0
1     Transportation is a large necessity in most co...          0
2     "America's love affair with it's vehicles seem...          0
3     How often do you ride in a car? Do you drive a...          0
4     Cars are a wonderful thing. They are perhaps o...          0
...                                                 ...        ...
1373  The Electoral College was originally establish...          0
1374  Dear senator, I think that the presidential el...          0
1375  The electoral college is a group of electors t...          0
1376  An electoral College compromises between elect...          0
1377  There has been a fuss about the Elector Colleg...          0

[1378 rows x 2 columns]

In [15]:
train = pd.concat([df , df1], axis =0)

In [16]:
train

                                                    text  generated
0      Cars. Cars have been around since they became ...          0
1      Transportation is a large necessity in most co...          0
2      "America's love affair with it's vehicles seem...          0
3      How often do you ride in a car? Do you drive a...          0
4      Cars are a wonderful thing. They are perhaps o...          0
...                                                  ...        ...
54686  I believe using cellphones in class for educat...          0
54687  Working alone, students do not have to argue w...          0
54688  "A problem is a chance for you to do your best...          0
54689  Many people disagree with Albert Schweitzer's ...          0
54690  Do you think that failure is the main thing fo...          0

[56069 rows x 2 columns]

In [17]:
test

         id  prompt_id          text
0  0000aaaa          2  Aaa bbb ccc.
1  1111bbbb          3  Bbb ccc ddd.
2  2222cccc          4  CCC ddd eee.

In [18]:
import re
import string
import nltk
from tqdm import tqdm
from nltk.corpus import stopwords 
# nltk.download('stopwords') 
stop_words = set(stopwords.words('english')) 
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
porter = PorterStemmer()

In [19]:
def remove_stop_words(sentence): 
    words = sentence.split() 
    filtered_words = []
    # Use a list comprehension to remove stop words 
    filtered_words = [word for word in words if word not in stop_words] 
    # Join the filtered words back into a sentence 
    return ' '.join(filtered_words)

# def remove_html(text):
#     pattern = re.compile('<.*?>')
#     return pattern.sub(r'',text)

def remove_punct(data):
    return data.translate(str.maketrans('','',string.punctuation))

# def remove_url(data):
#     pattern = re.compile(r'https?://\S+|www\.\S+')
#     return pattern.sub(r'',data)

def stem_sentence(sentence):
    tokens = word_tokenize(sentence)
    stemmed_tokens = [porter.stem(token) for token in tokens]
    return ' '.join(stemmed_tokens)

In [20]:
def preprocess(data):
    data['text'] = data['text'].str.lower()
    data['text'] = data['text'].apply(remove_punct)
    data['text'] = data['text'].apply(remove_stop_words)
    data['text'] = data['text'].apply(stem_sentence)
    return data

In [21]:
test = preprocess(test)

In [22]:
train=preprocess(train)

In [23]:
y = train['generated']

In [24]:
from gensim.models import Word2Vec
vector = Word2Vec(window=10,min_count=2)

In [25]:
vector_test = Word2Vec(window=10,min_count=2)

In [26]:
nlp = [nltk.word_tokenize(i) for i in train['text']  ]

In [27]:
nlp_test = [nltk.word_tokenize(i) for i in test['text']]

In [28]:
comp = nlp+ nlp_test

In [29]:
vector.build_vocab(comp)

In [30]:
vector.train(comp, total_examples=vector.corpus_count, epochs=vector.epochs)

(59367531, 65441950)

In [31]:
model  = vector.wv

In [32]:
def get_sentence_vector(word_list):
    word_vectors = [vector.wv[word] for word in word_list if word in vector.wv]
    if len(word_vectors) > 0:
        return np.mean(word_vectors, axis=0)
    else:
        return np.zeros(word2vec_model.vector_size)

In [33]:
train['final_txt'] = train['text'].apply(get_sentence_vector).tolist()
test['final_txt'] = test['text'].apply(get_sentence_vector).tolist()

In [34]:
train

,text,generated,final_txt
0,car car around sinc becam famou 1900 henri for...,0,"[1.5747164, -0.5290154, 1.0016595, 0.52618587,..."
1,transport larg necess countri worldwid doubt c...,0,"[1.5611144, -0.5091215, 0.99261224, 0.5423114,..."
2,america love affair vehicl seem cool say elisa...,0,"[1.5585432, -0.51826257, 0.97940665, 0.5437645..."
3,often ride car drive one motor vehicl work sto...,0,"[1.5566366, -0.51967436, 1.0093135, 0.5437808,..."
4,car wonder thing perhap one world greatest adv...,0,"[1.5804375, -0.53495955, 1.0284605, 0.59247774..."
...,...,...,...
54686,believ use cellphon class educ us goodbad idea...,0,"[1.3482174, -0.21741457, 0.9472239, 0.7208291,..."
54687,work alon student argu deciss proyect work som...,0,"[1.3942311, -0.38903826, 1.1512936, 0.7378516,..."
54688,problem chanc best think quot cant best everi ...,0,"[1.4508855, -0.45246124, 1.1537396, 0.5255891,..."
54689,mani peopl disagre albert schweitzer quot exam...,0,"[1.3795582, -0.44892865, 1.01009, 0.5881659, -..."
54690,think failur main thing peopl consist goal suc...,0,"[1.3606437, -0.44039366, 0.9597172, 0.651804, ..."

In [35]:
test

,id,prompt_id,text,final_txt
0,0000aaaa,2,aaa bbb ccc,"[1.5835662, -0.60239977, 0.17743346, -0.488733..."
1,1111bbbb,3,bbb ccc ddd,"[1.3854219, -0.6155105, 0.7903328, -0.03489531..."
2,2222cccc,4,ccc ddd eee,"[0.4542398, -0.12625745, 0.9538272, 0.04197763..."

In [36]:
X = train.copy()

In [37]:
vector_length = len(X.loc[0, 'final_txt'])
for i in range(vector_length):
    X[f'vector_dim_{i + 1}'] = X['final_txt'].apply(lambda x: x[i])
        
X.drop(columns =['final_txt','text','generated'],inplace = True)

In [38]:
t =test.copy()

In [39]:
vector_length = len(t.loc[0, 'final_txt'])
for i in range(vector_length):
    t[f'vector_dim_{i + 1}'] = t['final_txt'].apply(lambda x: x[i])

C:\Users\himanshu\AppData\Local\Temp\ipykernel_5788\1280389965.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  t[f'vector_dim_{i + 1}'] = t['final_txt'].apply(lambda x: x[i])
C:\Users\himanshu\AppData\Local\Temp\ipykernel_5788\1280389965.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  t[f'vector_dim_{i + 1}'] = t['final_txt'].apply(lambda x: x[i])

In [40]:
t

,id,prompt_id,text,final_txt,vector_dim_1,vector_dim_2,vector_dim_3,vector_dim_4,vector_dim_5,vector_dim_6,...,vector_dim_91,vector_dim_92,vector_dim_93,vector_dim_94,vector_dim_95,vector_dim_96,vector_dim_97,vector_dim_98,vector_dim_99,vector_dim_100
0,0000aaaa,2,aaa bbb ccc,"[1.5835662, -0.60239977, 0.17743346, -0.488733...",1.583566,-0.602400,0.177433,-0.488734,0.632495,1.655904,...,0.559852,0.128737,0.591205,1.477529,0.762851,1.852043,-1.155968,-1.361183,-0.679108,0.424631
1,1111bbbb,3,bbb ccc ddd,"[1.3854219, -0.6155105, 0.7903328, -0.03489531...",1.385422,-0.615511,0.790333,-0.034895,1.239548,2.227266,...,0.765015,1.415149,1.074524,3.064893,1.512438,1.997020,-0.804430,-0.979916,-1.008631,-0.182577
2,2222cccc,4,ccc ddd eee,"[0.4542398, -0.12625745, 0.9538272, 0.04197763...",0.454240,-0.126257,0.953827,0.041978,0.284724,0.875198,...,0.238827,1.132065,1.124320,1.981324,1.387326,1.321419,0.109281,-0.169526,-0.420019,-0.417554

In [41]:
X

       vector_dim_1  vector_dim_2
0          1.574716     -0.529015
1          1.561114     -0.509121
2          1.558543     -0.518263
3          1.556637     -0.519674
4          1.580438     -0.534960
...             ...           ...
54686      1.348217     -0.217415
54687      1.394231     -0.389038
54688      1.450886     -0.452461
54689      1.379558     -0.448929
54690      1.360644     -0.440394

[56069 rows x 2 columns]

In [42]:
y

0        0
1        0
2        0
3        0
4        0
        ..
54686    0
54687    0
54688    0
54689    0
54690    0
Name: generated, Length: 56069, dtype: int64

In [43]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [44]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
rfc=RandomForestClassifier()

In [46]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [47]:
y_pred=rfc.predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score

In [49]:
accuracy_score(y_test,y_pred)

0.626984126984127

In [50]:
import xgboost as xgb

In [51]:
xgb_i=xgb.XGBClassifier()

In [52]:
xgb_i.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [53]:
y_pred=xgb_i.predict(X_test)

In [54]:
accuracy_score(y_test,y_pred)

0.6542714464062779

In [55]:
from sklearn.neighbors import KNeighborsClassifier

In [56]:
knc=KNeighborsClassifier()

In [57]:
knc.fit(X_train,y_train)

KNeighborsClassifier()

In [58]:
y_pred=knc.predict(X_test)

In [59]:
accuracy_score(y_test,y_pred)

0.6141430354913501